name: Swift

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Debug Build
        run: xcodebuild -scheme Debug -project AutoGIF\ Spooler/AutoGIF\ Spooler.xcodeproj build
      - name: Release Build
        run: xcodebuild -scheme Release -project AutoGIF\ Spooler/AutoGIF\ Spooler.xcodeproj build
