name: Swift

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: xcodebuild -scheme "AutoGIF Spooler" -project AutoGIF\ Spooler/AutoGIF\ Spooler.xcodeproj build
