name: Swift

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Remove Code Sign Identity
        run: cat AutoGIF\ Spooler/AutoGIF\ Spooler.xcodeproj/project.pbxproj | sed -e 's/Mac Developer/-/g'
      - name: Build
        run: xcodebuild -scheme "AutoGIF Spooler" -project AutoGIF\ Spooler/AutoGIF\ Spooler.xcodeproj build
