name: XCode

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Remove Code Sign Identity
        run: sed -i .bak 's/Mac Developer/-/g' ./Captura/Captura.xcodeproj/project.pbxproj
      - name: Build
        run: xcodebuild -scheme "Captura" -project Captura/Captura.xcodeproj build
