name: XCode

on: [push]

jobs:
  build:

    runs-on: macos-12

    steps:
      - uses: actions/checkout@v2
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '13.3'
      - name: Remove Code Sign Identity
        run: sed -i .bak 's/Mac Developer/-/g' ./Captura/Captura.xcodeproj/project.pbxproj
      - name: Build
        run: xcodebuild -scheme "Captura" -project Captura/Captura.xcodeproj build
