name: XCode

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Remove Code Sign Identity
        run: sed -i .bak 's/Mac Developer/-/g' ./AutoGIF\ Spooler/AutoGIF\ Spooler.xcodeproj/project.pbxproj
      - name: Build
        run: xcodebuild -scheme "AutoGIF Spooler" -project AutoGIF\ Spooler/AutoGIF\ Spooler.xcodeproj build
