name: XCode

on: [push]

jobs:
  build:

    runs-on: macos-12

    steps:
      - uses: actions/checkout@v2
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '13.3'
      - name: Remove Code Sign Identity
        run: sed -i .bak 's/Mac Developer/-/g' ./Captura/Captura.xcodeproj/project.pbxproj
      - name: Switch XCode Version
        run: |
          xcode-select --print-path > current-xcode.txt
          sed -i .back 's/[0-9][0-9]*\.[0-9][0-9]*\.*[0-9]*/13\.3/g' current-xcode.txt
          cat current-xcode.txt | sudo xcode-select -switch `xargs`
          cat current-xcode.txt
      - name: Build
        run: xcodebuild -scheme "Captura" -project Captura/Captura.xcodeproj build
